# db1
spring:
  datasource:
    driver-class-name: XXX
    url: XXX
    username: XXX
    password: XXX

#db 2
other:
  datasource:
    driver-class-name: XXX
    url: XXX
    username: XXX
    password: XXX

